[project]
name = "logs2report"
version = "0.1.0"
description = "CLI app para transformar logs a reporte tabular."
readme = "README.md"
authors = [
    { name = "Isaul Tirado", email = "tiradolisaul@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
logs2report = "logs2report:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
